version: "3.7"

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "6831:6831/udp"
      - "16686:16686"
      - "14250:14250" 

  otel:
    build: 
      context: ./
      dockerfile: ./Dockerfile
    container_name: otel
    depends_on:
      - jaeger
    ports:
      - "4333:4333"   
    volumes:
      - ./otel_connector/collet-config.yaml:/app/collet-config.yaml 
    

    

 
   