extensions:
  tokenauth:
    #scheme: "Bearer"
    token: "dev"

receivers:
  otlp:
    protocols:
      grpc:
        auth:
          authenticator: "tokenauth"

exporters:
  jaeger:
    endpoint: "127.0.0.1:14250"
    tls:
      insecure: true

  elasticsearch:
    endpoints: ["http://127.0.0.1:9200"]
    traces_index: trace_index

processors:
  batch:

# extensions:
#   health_check:
#   pprof:
#     endpoint: :1888
#   zpages:
#     endpoint: :55679

service:
  extensions: [tokenauth]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger, elasticsearch]
