extensions:
  tokenauth:
    #scheme: "Bearer"
    token: "dev"

receivers:
  otlp:
    protocols:
      grpc:
        auth:
          authenticator: "tokenauth"

exporters:
  # prometheus:
  #   endpoint: "127.0.0.1:8889"
  #   const_labels:
  #     label1: value1

  logging:
    verbosity: detailed

  # zipkin:
  #   endpoint: "http://127.0.0.1:9411/api/v2/spans"
  #   format: proto

  jaeger:
    endpoint: "jaeger:14250"
    tls:
      insecure: true

  debug:
    verbosity: detailed

processors:
  batch:

# extensions:
#   health_check:
#   pprof:
#     endpoint: :1888
#   zpages:
#     endpoint: :55679

service:
  extensions: [tokenauth]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, jaeger, debug]
    # metrics:
    #   receivers: [otlp]
    #   processors: [batch]
    #   exporters: [logging, prometheus]
